import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],  
  subsets: ["thai", "latin"],
});


export const metadata: Metadata = {
  title: "Varity Calulate Website",
  description: "Generated by create next app",
  keywords: ["Varity Calculate", "เครืื่องคิดเลช", "คำนวณ"],
  authors: [{ 
    name: "Sinlapachai" 
  , url: "https://github.com/sinlapachai"
  }],

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className}`}
      >
        {children}
      </body>
    </html>
  );
}
